version: '3'

services:
  gateway:
    image: nginx:latest
    container_name: gateway
    restart: always
    ports:
      - 12345:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 100M

  upstream1:
    image: istio/fortio:latest
    container_name: upstream1
    restart: always
  upstream2:
    image: istio/fortio:latest
    container_name: upstream2
    restart: always
  upstream3:
    image: istio/fortio:latest
    container_name: upstream3
    restart: always
