version: '3'

services:
  gateway:
    image: nginx:latest
    container_name: gateway
    restart: always
    ports:
      - 12345:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: '0.02'
          memory: 50M

  upstream:
    image: istio/fortio:latest
    container_name: upstream1
    restart: always
