version: "3"

services:
  upstream1:
    image: istio/fortio:latest
    container_name: upstream1
    restart: always
  upstream2:
    image: istio/fortio:latest
    container_name: upstream2
    restart: always
  upstream3:
    image: istio/fortio:latest
    container_name: upstream3
    restart: always
