name: http-proxy

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

env:
  SCRIPT_DIR: "${{ github.workspace }}/script"
  DOCKER_STATS_SHELL: "${{ github.workspace }}/script/docker_stats.sh"
  LIMITED_DIR: "${{ github.workspace }}/docs/http-proxy/limited"

jobs:
  limited:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.LIMITED_DIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: ./.github/workflows/k6_limited.yaml

      # - uses: softprops/action-gh-release@v2
      #   with:
      #     name: "limited"
      #     tag_name: "limited"
      #     files: |
      #       ${{ env.LIMITED_DIR }}/docker_stats_raw.csv
      #       ${{ env.LIMITED_DIR }}/docker_stats.csv
      #       ${{ env.LIMITED_DIR }}/k6_summery.json
