name: http-proxy

on:
  push:
    branches:
      - master
      - main

jobs:
  limited-cpu50:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Run Containers
        run: |
          cd ./docs/http-proxy/limited/
          docker compose --file=docker-compose-cpu50.yaml up -d
          for i in {1..20}; do curl --max-time 5 localhost:12345 && break; done
      - run: docker ps -a
      - uses: grafana/setup-k6-action@v1
      - run: k6 -v
