name: http-proxy

on:
  push:
    branches:
      - master
      - main

env:
  SCRIPT_DIR: "${{ github.workspace }}script/"
  DOCKER_STATS_SHELL: "${{ github.workspace }}script/docker_stats.sh"

jobs:
  limited:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    defaults:
      run:
        shell: bash
        working-directory: "${{ github.workspace }}docs/http-proxy/limited/"
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Run Containers
        run: |
          docker compose --file=docker-compose-50m.yaml up -d
          sleep 10
          for i in {1..20}; do curl --max-time 5 localhost:12345 && break; done
      - run: docker ps -a
      - run: |
          cp $DOCKER_STATS_SHELL ./
          ./docker_stats.sh &
          sleep 10
      - uses: grafana/setup-k6-action@v1
      - run: k6 run k6_script.js -q --no-thresholds
      - run: |
          sleep 10
          pid=$(cat docker_stats.pid)
          kill -15 $(pid)
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ./docker_stats_raw.csv
            ./docker_stats.csv
            ./k6_summery.json
