name: http-proxy

on:
  push:
    branches:
      - master
      - main

env:
  SCRIPT_DIR: "${{ github.workspace }}/script"
  DOCKER_STATS_SHELL: "${{ github.workspace }}/script/docker_stats.sh"
  LIMITED_DIR: "${{ github.workspace }}/docs/http-proxy/limited"
jobs:
  limited:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.LIMITED_DIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Run Containers
        run: |
          docker compose --file=docker-compose-50m.yaml up -d
          sleep 10
          for i in {1..20}; do curl -v --max-time 5 localhost:12345 && break; done
      - run: docker ps -a
      - run: |
          cp $DOCKER_STATS_SHELL ./
          chmod +x ./docker_stats.sh
          ./docker_stats.sh &
          sleep 10
      - uses: grafana/setup-k6-action@v1
      - run: k6 run k6_script.js -q --no-thresholds
      - run: |
          sleep 10
          pid=$(cat docker_stats.pid)
          kill -15 ${pid}
      - uses: actions/upload-artifact@v2
        with:
          name: result
          if-no-files-found: error
          path: |
            ${LIMITED_DIR}/docker_stats_raw.csv
            ${LIMITED_DIR}/docker_stats.csv
            ${LIMITED_DIR}/k6_summery.json
